import json
import math
from pathlib import Path
from typing import Dict, List, Any
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

def process(payload: dict) -> dict:
    # ---------------------------------------------------------------
    # 0. 解析 payload
    # ---------------------------------------------------------------
    experiments = payload['experiments']
    output_dir = Path(payload['output_dir'])
    parameters = payload['parameters']
    analysis_goal = parameters.get('analysis_goal', '')
    workflow = parameters.get('workflow', {})
    unmaintained_ids = workflow.get('unmaintained_experiment_ids', [])
    # 如果没有指定，从analysis_goal中提取目标实验，但这里按优先处理workflow指定的
    target_new_ids = set(unmaintained_ids) if unmaintained_ids else {'exp_28','exp_29','exp_30','exp_31','exp_32','exp_33'}
    # 所有实验ID
    all_ids = list(experiments.keys())

    # ---------------------------------------------------------------
    # 1. 为未维护的实验定义派生序列 v 和 a
    # ---------------------------------------------------------------
    derived_series = []
    for eid in target_new_ids:
        if eid not in experiments:
            continue
        exp = experiments[eid]
        series_dict = exp['series']
        available = set(exp.get('available_series', []))
        # 检查是否已定义
        if 'v' in available and 'a' in available:
            # 已存在，跳过定义
            continue
        if 't' not in available or 'q' not in available:
            continue
        t = np.array(series_dict['t'])
        q = np.array(series_dict['q'])
        # 计算 v = dq/dt
        v = np.gradient(q, t, edge_order=2)
        # 计算 a = dv/dt
        a = np.gradient(v, t, edge_order=2)
        # 只有当尚未定义时才添加
        if 'v' not in available:
            derived_series.append({
                'experiment_id': eid,
                'name': 'v',
                'values': v.tolist(),
                'source_name': 'np.gradient(q, t, edge_order=2)',
                'provenance': 'generated by process: maintain_ledger v from q',
                'description': f'Derived velocity for {eid} using central differences'
            })
        if 'a' not in available:
            derived_series.append({
                'experiment_id': eid,
                'name': 'a',
                'values': a.tolist(),
                'source_name': 'np.gradient(v, t, edge_order=2)',
                'provenance': 'generated by process: maintain_ledger a from v',
                'description': f'Derived acceleration for {eid} using central differences'
            })

    # ---------------------------------------------------------------
    # 2. 对所有常数场实验进行 a-v 线性回归
    # 常数场: force_field_type='constant' 且 F_ext != 0
    # ---------------------------------------------------------------
    constant_experiments = []
    free_experiments = []
    for eid in all_ids:
        exp = experiments[eid]
        config = exp['config']
        force_type = config.get('force_field_type', '')
        F_ext = config.get('F_ext', 0.0)
        if force_type == 'constant' and abs(F_ext) > 1e-12:
            constant_experiments.append(eid)
        elif force_type == 'free' or abs(F_ext) < 1e-12:
            free_experiments.append(eid)

    # 确保我们需要的自由场包含在内
    free_targets = ['exp_01', 'exp_04', 'exp_33']
    # 对每个常数场实验，获取 v,a 序列并回归
    obs_list = []
    regression_results = []  # 存储每个实验的回归参数
    for eid in constant_experiments:
        exp = experiments[eid]
        config = exp['config']
        F_ext = config['F_ext']
        v0 = config.get('initial_v', 0.0)
        series = exp['series']
        available = set(exp.get('available_series', []))
        if 'v' not in available or 'a' not in available:
            # 确保有v,a，如果没有，尝试从q,t生成（但之前已经处理了new，这里可能遗漏）
            # 如果还是缺失，则跳过回归
            continue
        v = np.array(series['v'])
        a = np.array(series['a'])
        # 线性回归 a = slope * v + intercept
        X = v.reshape(-1, 1)
        y = a
        reg = LinearRegression(fit_intercept=True)
        reg.fit(X, y)
        slope = reg.coef_[0]
        intercept = reg.intercept_
        # 预测和误差
        y_pred = reg.predict(X)
        r2 = r2_score(y, y_pred)
        rmse = math.sqrt(mean_squared_error(y, y_pred))
        # 记录
        result_entry = {
            'experiment_id': eid,
            'F_ext': F_ext,
            'v0': v0,
            'slope': slope,
            'intercept': intercept,
            'R2': r2,
            'RMSE': rmse
        }
        regression_results.append(result_entry)

        obs_summary = f"常数场实验 {eid} a-v 线性回归：斜率={slope:.6f}, 截距={intercept:.6f}, R²={r2:.6f}, RMSE={rmse:.6f}。F_ext={F_ext}, v0={v0}"
        obs_list.append({
            'summary': obs_summary,
            'source_data_refs': [f'{eid}:v', f'{eid}:a'],
            'metrics': {
                'experiment_id': eid,
                'slope': slope,
                'intercept': intercept,
                'R2': r2,
                'RMSE': rmse,
                'F_ext': F_ext,
                'v0': v0
            }
        })

    # ---------------------------------------------------------------
    # 3. 跨实验汇总回归
    # ---------------------------------------------------------------
    # 建立 DataFrame 以便后续回归
    df = pd.DataFrame(regression_results)
    n_const = len(df)
    if n_const >= 2:
        # 3a 截距 vs F_ext 一元线性回归
        X_intercept = df['F_ext'].values.reshape(-1, 1)
        y_intercept = df['intercept'].values
        reg_inter = LinearRegression().fit(X_intercept, y_intercept)
        slope_inter = reg_inter.coef_[0]
        intercept_inter = reg_inter.intercept_
        y_pred_inter = reg_inter.predict(X_intercept)
        r2_inter = r2_score(y_intercept, y_pred_inter)
        rmse_inter = math.sqrt(mean_squared_error(y_intercept, y_pred_inter))
        obs_inter = {
            'summary': f"跨实验截距与F_ext线性回归：斜率={slope_inter:.6f}, 截距={intercept_inter:.6f}, R²={r2_inter:.6f}, RMSE={rmse_inter:.6f}。基于{n_const}个常数场实验。",
            'source_data_refs': [f'{eid}:a-v-regression' for eid in constant_experiments],
            'metrics': {
                'regression_type': 'intercept_vs_F_ext',
                'slope': slope_inter,
                'intercept': intercept_inter,
                'R2': r2_inter,
                'RMSE': rmse_inter,
                'n_experiments': n_const
            }
        }
        obs_list.append(obs_inter)

        # 3b 斜率 vs v0 一元线性回归
        df_slope = df.dropna(subset=['v0'])
        if len(df_slope) >= 2:
            X_slope = df_slope['v0'].values.reshape(-1, 1)
            y_slope = df_slope['slope'].values
            reg_slope = LinearRegression().fit(X_slope, y_slope)
            slope_s = reg_slope.coef_[0]
            intercept_s = reg_slope.intercept_
            y_pred_s = reg_slope.predict(X_slope)
            r2_s = r2_score(y_slope, y_pred_s)
            rmse_s = math.sqrt(mean_squared_error(y_slope, y_pred_s))
            obs_slope = {
                'summary': f"跨实验斜率与v0线性回归：斜率={slope_s:.6f}, 截距={intercept_s:.6f}, R²={r2_s:.6f}, RMSE={rmse_s:.6f}。基于{len(df_slope)}个常数场实验。",
                'source_data_refs': [f'{eid}:a-v-regression' for eid in df_slope['experiment_id']],
                'metrics': {
                    'regression_type': 'slope_vs_v0',
                    'slope': slope_s,
                    'intercept': intercept_s,
                    'R2': r2_s,
                    'RMSE': rmse_s,
                    'n_experiments': len(df_slope)
                }
            }
            obs_list.append(obs_slope)

        # 3c 截距 vs F_ext 和 v0 二元线性回归
        if 'v0' in df.columns and df['v0'].notna().all():
            X_multi = df[['F_ext', 'v0']].values
            y_multi = df['intercept'].values
            reg_multi = LinearRegression().fit(X_multi, y_multi)
            y_pred_multi = reg_multi.predict(X_multi)
            r2_multi = r2_score(y_multi, y_pred_multi)
            rmse_multi = math.sqrt(mean_squared_error(y_multi, y_pred_multi))
            coef_F = reg_multi.coef_[0]
            coef_v0 = reg_multi.coef_[1]
            inter_multi = reg_multi.intercept_
            obs_multi = {
                'summary': f"截距对F_ext和v0的二元线性回归：系数=[{coef_F:.6f}, {coef_v0:.6f}], 截距={inter_multi:.6f}, R²={r2_multi:.6f}, RMSE={rmse_multi:.6f}。基于{n_const}个常数场实验。",
                'source_data_refs': [f'{eid}:a-v-regression' for eid in constant_experiments],
                'metrics': {
                    'regression_type': 'intercept_vs_F_ext_v0',
                    'coef_F_ext': coef_F,
                    'coef_v0': coef_v0,
                    'intercept': inter_multi,
                    'R2': r2_multi,
                    'RMSE': rmse_multi,
                    'n_experiments': n_const
                }
            }
            obs_list.append(obs_multi)

    # ---------------------------------------------------------------
    # 4. 检查自由场实验 a 接近 0
    # ---------------------------------------------------------------
    free_check_obs = None
    zero_check_ok = True
    check_details = {}
    for free_id in free_targets:
        if free_id not in experiments:
            continue
        exp = experiments[free_id]
        config = exp['config']
        series = exp['series']
        available = set(exp.get('available_series', []))
        if 'a' not in available:
            # 可能没有a，尝试生成但这里不主动生成（避免重复），跳过
            continue
        a = np.array(series['a'])
        mean_a = np.mean(a)
        std_a = np.std(a)
        max_abs = np.max(np.abs(a))
        if max_abs > 1e-10:
            zero_check_ok = False
        check_details[free_id] = {'mean': mean_a, 'std': std_a, 'max_abs': max_abs}
    if check_details:
        summary_parts = []
        for eid, vals in check_details.items():
            summary_parts.append(f"{eid}: mean_a={vals['mean']:.2e}, std={vals['std']:.2e}, max_abs={vals['max_abs']:.2e}")
        summary = "自由场实验a接近0检查：" + "; ".join(summary_parts)
        free_check_obs = {
            'summary': summary,
            'source_data_refs': [f'{eid}:a' for eid in check_details],
            'metrics': {
                'free_check_mean': {eid: v['mean'] for eid, v in check_details.items()},
                'free_check_std': {eid: v['std'] for eid, v in check_details.items()},
                'free_check_max_abs': {eid: v['max_abs'] for eid, v in check_details.items()},
                'all_near_zero': zero_check_ok
            }
        }
        obs_list.append(free_check_obs)

    # ---------------------------------------------------------------
    # 5. 生成诊断图（非必需，但有助于决策）
    # ---------------------------------------------------------------
    figures = []
    if n_const >= 2:
        # 图1: 截距 vs F_ext
        fig1, ax1 = plt.subplots()
        ax1.scatter(df['F_ext'], df['intercept'], c='blue', label='data')
        # 回归线
        x_range = np.linspace(df['F_ext'].min(), df['F_ext'].max(), 100)
        y_line = slope_inter * x_range + intercept_inter
        ax1.plot(x_range, y_line, 'r--', label=f'fit: y={slope_inter:.3f}x+{intercept_inter:.3f}')
        ax1.set_xlabel('F_ext')
        ax1.set_ylabel('intercept')
        ax1.set_title('intercept vs F_ext (constant experiments)')
        ax1.legend()
        fpath1 = output_dir / 'intercept_vs_F_ext.png'
        fig1.savefig(str(fpath1), dpi=100)
        plt.close(fig1)
        figures.append(str(fpath1))

        # 图2: 斜率 vs v0
        if 'v0' in df.columns and df_slope.shape[0] >= 2:
            fig2, ax2 = plt.subplots()
            ax2.scatter(df_slope['v0'], df_slope['slope'], c='green')
            x_range2 = np.linspace(df_slope['v0'].min(), df_slope['v0'].max(), 100)
            y_line2 = slope_s * x_range2 + intercept_s
            ax2.plot(x_range2, y_line2, 'r--', label=f'fit: y={slope_s:.3f}x+{intercept_s:.3f}')
            ax2.set_xlabel('v0')
            ax2.set_ylabel('slope')
            ax2.set_title('slope vs v0 (constant experiments)')
            ax2.legend()
            fpath2 = output_dir / 'slope_vs_v0.png'
            fig2.savefig(str(fpath2), dpi=100)
            plt.close(fig2)
            figures.append(str(fpath2))

    # ---------------------------------------------------------------
    # 6. 组装最终返回
    # ---------------------------------------------------------------
    # 观察总结
    n_new_def = len(derived_series)
    n_reg = len(regression_results)
    obs_count = len(obs_list)
    observation = f"维护实验数据记录表完成。为{len(target_new_ids)}个新实验定义了{n_new_def}个派生序列（v和a）。对{n_const}个常数场实验进行了a-v线性回归，共{n_reg}个实验回归。生成了{obs_count}条OBS记录，包括跨实验回归和自由场检查。未宣布任何定律。"
    metrics = {
        'derived_series_count': n_new_def,
        'constant_experiment_regressions': n_reg,
        'observation_count': obs_count,
        'figure_count': len(figures)
    }
    # 如果自由场检查有结果，加入指标
    if free_check_obs:
        metrics['free_experiments_checked'] = len(free_targets)
        metrics['free_check_all_zero'] = zero_check_ok

    return {
        'observation': observation,
        'derived_series': derived_series,
        'observations': obs_list,
        'validations': [],
        'figures': figures,
        'metrics': metrics
    }
